min_version = "2026.9.11"

[tools]
jq = "latest"
lazygit = "latest"
terminal-control = { version = "1.2.1-r1", version_prefix = "musl-v", os = ["linux/x64"] }

[tool_alias]
terminal-control = "github:dhth/terminal-control"

[shell_alias]
g = "git"
lg = "lazygit"
v = "vim"

[dotfiles]
"~/.config" = { source = "config", mode = "copy", manifest = "git" }
"~/.claude/CLAUDE.md" = { source = "claude/CLAUDE.md", mode = "copy" }
