min_version = "2026.9.11"

[tools]
lazygit = "latest"
terminal-control = { version = "0.6.0-r1", version_prefix = "musl-v", os = ["linux/x64"] }

[tool_alias]
terminal-control = "github:dhth/terminal-control"

[shell_alias]
g = "git"
lg = "lazygit"
v = "vim"

[dotfiles]
"~/.config" = { source = "config", mode = "copy", manifest = "git" }
