promptToReturnFromSubprocess: false
disableStartupPopups: true
git:
  autoFetch: true
gui:
  showRandomTip: false
  showCommandLog: false
  screenMode: normal
  sidePanels:
    - [files]
    - [branches]
    - [commits]
